service: webhooks-func

provider:
  name: aws
  runtime: python3.7
  region: ${env:REGION}

package:
  include:
    - ./webhook
    - ./requirements.txt

plugins:
  - serverless-python-requirements

# resources
resources:
  Outputs:
    ApiId:
      Value:
        Ref: 'ApiGatewayRestApi'

# plugins:
#   - serverless-pseudo-parameters

# lambda functions
functions:
  create:
    handler: webhook/consumer.consume
    vpc:
      securityGroupIds:
        - ${cf:webhook-networking-dev.DBSecurityGroupId.Value}
      subnetIds:
        - ${cf:webhook-networking-dev.DBPrivSubnetId.Value}
    environment:
      DB_PRIVATE_HOSTNAME: ${cf:webhook-db-dev.DBInstanceDNSInternal.Value}
      POSTGRES_PASS: ${env:POSTGRES_PASS}
    events:
      - http:
          path: consume
          method: post
          cors: true
          integration: lambda
